# Setup
title:               One frame movies
tagline:             'One frame movies.'
description:         'One frame movies...'
url:                 https://genkistation.github.io/oneframemovies/
baseurl:             '/oneframemovies'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Genkistation
  url:               https://genkistation.github.io/website
  email:             genkistationprod@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
